### ISSUE TITLE
Failed to load dynamic library 'libz3'

### ISSUE THREAD

**Issue by spydon** [pingbird/dz3#1]
Hi, thanks for what looks like a great library!
I think most people doing Advent of Code part 2 in Dart today will be using it. :smile: 

However I'm having a problem, which may very well be me doing something wrong:

```console
year2023 git:main ❯ dart lib/day_24_2.dart | tee /dev/tty | wl-copy         ✹ ✭
Unhandled exception:
Invalid argument(s): Failed to load dynamic library 'libz3': libz3: cannot open shared object file: No such file or directory
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:43)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22:12)
#2      _libz3 (package:z3/src/z3.dart:16:54)
#3      _libz3 (package:z3/src/z3.dart)
#4      new Config (package:z3/src/z3.dart:455:19)
#5      rootContext (package:z3/src/scoped.dart:11:53)
#6      currentContext (package:z3/src/scoped.dart:20:48)
#7      solver (package:z3/src/scoped.dart:926:18)
#8      main (package:year2023/day_24_2.dart:34:13)
#9      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#10     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

And I have z3 installed and it looks like it should be accessible:

```console
year2023 git:main ❯ ldconfig -p | grep libz3                                ✹ ✭
	libz3.so.4 (libc6,x86-64) => /lib/x86_64-linux-gnu/libz3.so.4
	libz3.so (libc6,x86-64) => /lib/x86_64-linux-gnu/libz3.so
```

Any idea what might be wrong?

**Comment by spydon** [comment]
Ah, when I changed line 16 of `z3.dart` to the following it works (adding `.so`):
```dart
final _libz3 = Z3Lib(libz3Override ?? DynamicLibrary.open('libz3.so'));
```

**Comment by pingbird** [comment]
This will be fixed in the next release, thanks!

**Comment by Ecateln** [comment]
@pingbird do you have an ETA for when this next release will come out ? I'm personally comfortable with editing the file myself, but this may not also be the case of the people I'm currently working with..
